### ISSUE TITLE
Fiat sending usability

### ISSUE THREAD

**Issue by jacogr** [theblock/theblock.github.io#21]
Watching the girlfriend last night sending the weekly pocket money to the kids, some comments.

First one went off without a hitch. Maybe some rounding/display issues where it shows 9.99 for the EUR 10 requested. (Not a major one, explainable.)

For the second one the wheels came off a tiny bit. First attempt the ETH/USD/EUR toggle was not used and when it got to the confirmation screen, she was not 100% if she requested ETH or EUR. At this point it probably would make sense to display the actual total value in the selected currency as well. (It aligns with the rest)

After aborting (it was ETH not EUR), it was done again. Now the flow gets in the way a bit - input 10, change the currency to EUR, now go back and edit the 2k (ETH -> fiat) down to the requested 10. So instead of interacting with a single field once, it was done twice. The auto-convert is nice, but it may make sense to stick to not converting until sent. (Or the flow could probably be optimised to only do things once.)

**Comment by xavieryvez** [comment]
Agreed on both cases, it is not perfect. Will spend some time here and see what approach works best for the intended outcome.

**Comment by xavieryvez** [comment]
Still have the display of the total/fiat value inside the send popup. However, need to rework that popup to be nicer (some inspiration required).
